source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-param'
gem 'sinatra-flash'
gem 'sinatra-activerecord'
gem "activesupport"
gem 'activerecord'
gem 'sanitize'
gem 'erubis'
gem 'json'
gem 'thin'
gem 'rake'
gem 'rack-flash'
gem 'unicorn'
gem 'rdiscount'
gem 'bundler-audit'
gem 'uuid'
gem 'mysql2'
gem 'ipaddress'
gem 'httparty'
gem 'bcrypt'
gem 'uuidtools'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

group :test, :development do
  gem 'rspec'
  gem 'random-word'
  gem 'shotgun'
  gem 'minitest'
  gem 'rack-test'
  gem 'sqlite3'
  gem 'pry'
  gem 'awesome_print', '~> 1.2.0'
  gem 'turn'
  gem 'ansi'
  gem 'page-object'
end